Repository tmmdata/foundation-php-sdk, pull requests merged in 2020-03, with the labels that each got.

#1 Add information about custom fields.
  README.md
Labels: enhancement

#2 Clean up the Custom Field JSON object
  README.md
Labels: bug

#3 Composer setup
  composer.json
  src/TMMData/Foundation.class.php
Labels: enhancement

#4 Composer fixes
  README.md
  src/TMMData/Foundation.php
Labels: bug, enhancement
